"""
Django settings for possystem project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# Security settings loaded from environment variables
# CRITICAL: These MUST be set in production - no defaults provided
SECRET_KEY = config('SECRET_KEY')

# Fernet Key for Field Encryption
# Generate with: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
FERNET_KEY = config('FERNET_KEY').encode()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# Allowed hosts from environment (comma-separated list)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1,.localhost', cast=Csv())

# Root domain for subdomain routing and links
ROOT_DOMAIN = config('ROOT_DOMAIN', default='localhost:8000')


# Application definition

SHARED_APPS = (
    'django_tenants',  # mandatory
    'tinymce',
    'unfold',
    'unfold.contrib.filters',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.sitemaps',
    'django.contrib.sites',
    'daphne',  # Must be before staticfiles
    'django.contrib.staticfiles',
    'channels',
    'django.contrib.humanize',
    
    # REST API
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'django_filters',
    'corsheaders',
    
    # Custom apps
    'accounts',  # Contains Tenant model
    'billing',   # Subscriptions/Plans usually shared
    'notifications', # Shared for now
    'documentation', # User manual/help content
    'api',  # Centralized API app
    'csp',  # Content Security Policy
)

TENANT_APPS = (
    'main',
    'branches',
    'storefront',
    'kiosk',
    'wallet',
)

INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]

TENANT_MODEL = "accounts.Tenant"
TENANT_DOMAIN_MODEL = "accounts.Domain"

MIDDLEWARE = [
    'django_tenants.middleware.main.TenantMainMiddleware', # Added for tenancy
    'api.middleware.APISubdomainMiddleware',  # Route api. and developer. subdomains
    'django.middleware.security.SecurityMiddleware',
    # 'possystem.middleware_db.ReplicaHealthCheckMiddleware',  # Moved to conditional
    'django.middleware.gzip.GZipMiddleware',  # Added for GZip compression
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware', # Added for CORS
    'django.middleware.common.CommonMiddleware',
    'api.middleware.APIKeyCsrfExemptMiddleware',  # Exempt API key requests from CSRF
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'accounts.middleware.TenantProfileMiddleware',  # Attach correct profile for current tenant
    'accounts.middleware.StrictAccessMiddleware',   # Isolate Developer and Merchant dashboards
    'main.middleware.CurrentUserMiddleware',  # Track current user for history
    'possystem.middleware_logging.CorrelationIDMiddleware',  # Add correlation IDs for request tracking
    'accounts.middleware.CrossTenantAuditMiddleware',  # Track cross-tenant access
    'api.middleware.APIRateLimitMiddleware',  # API rate limiting
    'api.middleware.APIAuditMiddleware',  # API request audit logging
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # 'possystem.middleware.SubdomainMiddleware', # REMOVED: Conflicts with django-tenants
    'possystem.middleware.TwoFAMiddleware',
    'billing.middleware.SubscriptionMiddleware',  # Enforce subscription restrictions
    # 'csp.middleware.CSPMiddleware', # CSP Support
]




X_FRAME_OPTIONS = 'SAMEORIGIN'

ROOT_URLCONF = 'possystem.urls'
PUBLIC_SCHEMA_URLCONF = 'possystem.urls' # Ensure public schema uses the main URL config

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.csrf',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'notifications.context_processors.notifications',
                'possystem.context_processors.tenant_context',
                'accounts.context_processors.api_key_processor',
                'main.context_processors.currency_processor',
                'branches.context_processors.branch_currency',  # Global branch currency
                'accounts.context_processors.seo_settings', # Global SEO settings
                # 'csp.context_processors.nonce',
            ],
        },
    },
]

SITE_ID = 1

WSGI_APPLICATION = 'possystem.wsgi.application'
ASGI_APPLICATION = 'possystem.asgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django_tenants.postgresql_backend',  # Must use tenants backend
        'NAME': config('DB_NAME', default='puxbay'),
        'USER': config('DB_USER', default='puxbay'),
        'PASSWORD': config('DB_PASSWORD', default='Thinkce@softivitepuxbay'),
        'HOST': '127.0.0.1' if config('DB_HOST', default='127.0.0.1') == 'localhost' else config('DB_HOST'),
        'PORT': config('DB_PORT', default='5432'),
        'CONN_MAX_AGE': 600,
        'OPTIONS': {
            'connect_timeout': 10,
        }
    },
}




# Database routers - order matters!
DATABASE_ROUTERS = [
    'django_tenants.routers.TenantSyncRouter',
]



# Channel Layers for WebSockets
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [config('REDIS_URL', default='redis://localhost:6379/1')],
        },
    },
}

# Session Engine (moved to bottom or keep here if preferred)
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"
SESSION_COOKIE_SECURE = False
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_DOMAIN = None
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_SAMESITE = 'Lax'


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Stripe Configuration
STRIPE_PUBLISHABLE_KEY = config('STRIPE_PUBLISHABLE_KEY', default='')
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY', default='')
STRIPE_WEBHOOK_SECRET = config('STRIPE_WEBHOOK_SECRET', default='')
DOMAIN_URL = config('DOMAIN_URL', default='http://localhost:8000/')

# Email Backend (Console for Development, configure for production)
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@localhost')
EMAIL_SUBJECT_PREFIX = config('EMAIL_SUBJECT_PREFIX', default='[Puxbay] ')

# Paystack Configuration
PAYSTACK_PUBLIC_KEY = config('PAYSTACK_PUBLIC_KEY', default='')
PAYSTACK_SECRET_KEY = config('PAYSTACK_SECRET_KEY', default='')

# Monitoring & Error Tracking

# Content Security Policy (CSP) Settings
# Allow self, Stripe, Paystack, and standard CDNs
# Using django-csp 4.0+ dictionary format
# CONTENT_SECURITY_POLICY = {
#     "DIRECTIVES": {
#         "default-src": ["'self'"],
#         "script-src": [
#             "'self'",
#             "'unsafe-eval'", # Required for Alpine.js (Unfold Admin)
#             "https://js.stripe.com",
#             "https://js.paystack.co",
#             "https://cdn.jsdelivr.net",
#             "https://unpkg.com",
#             "cdnjs.cloudflare.com",
#             "ajax.googleapis.com", 
#             "code.jquery.com", 
#             "https://*.tiny.cloud",
#             "https://*.tinymce.com",
#             "blob:"
#         ],
#         "style-src": [
#             "'self'",
#             "'unsafe-inline'", # Needed for many libraries, using nonces where possible
#             "https://cdn.jsdelivr.net",
#             "https://*.paystack.com",
#             "https://unpkg.com",
#             "https://*.tiny.cloud",
#             "https://*.tinymce.com",
#             "data:"
#         ],
#         "font-src": [
#             "'self'",
#             "https://cdn.jsdelivr.net",
#             "data:"
#         ],
#         "img-src": [
#             "'self'",
#             "data:",
#             "blob:",
#             "https://*.stripe.com",
#             "https://*.paystack.com",
#             "https://*.cloudfront.net",
#             "https://*.amazonaws.com", # For S3 if used
#             "https://*.tiny.cloud",
#             "https://*.google-analytics.com",
#             "https://*.facebook.com"
#         ],
#         "frame-src": [
#             "'self'",
#             "https://js.stripe.com",
#             "https://*.paystack.co",
#             "https://*.paystack.com",
#             "https://checkout.paystack.com",
#             "https://*.tiny.cloud"
#         ],
#         "media-src": [
#             "'self'",
#             "data:",
#             "https://assets.mixkit.co",
#         ],
#         "connect-src": [
#             "'self'",
#             "https://api.stripe.com",
#             "https://*.paystack.co",
#             "https://*.paystack.com",
#             "https://unpkg.com",
#             "https://api.qrserver.com",
#             "ws:",
#             "wss:",
#             "https://*.tiny.cloud",
#             "https://*.tinymce.com",
#             "https://*.google-analytics.com",
#             "https://*.facebook.com"
#         ],
#         "worker-src": ["'self'", "blob:", "data:"],
#     }
# }
# # Legacy setting for inclusion of nonces
# CSP_INCLUDE_NONCE_IN = ["script-src"]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Auth Settings
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'landing'

# Django Unfold Configuration
def get_site_title(request):
    """Dynamic site title showing current tenant"""
    try:
        from django.db import connection
        schema_name = getattr(connection, 'schema_name', 'public')
        
        if schema_name == 'public':
            return "Puxbay Admin - Global"
        else:
            try:
                from accounts.models import Tenant
                tenant = Tenant.objects.get(schema_name=schema_name)
                return f"Puxbay Admin - {tenant.name}"
            except:
                return f"Puxbay Admin - {schema_name}"
    except:
        return "Puxbay Admin"

UNFOLD = {
    "SITE_TITLE": get_site_title,
    "SITE_HEADER": "Puxbay Admin",
    "SITE_URL": "/",
    "SITE_ICON": {
        "light": "/static/images/icon-192.png",
        "dark": "/static/images/icon-192.png",
    },
    "SHOW_SEARCH": False,
    "ENVIRONMENT": "possystem.settings.get_environment_badge",
    "DASHBOARD_CALLBACK": "possystem.dashboard.dashboard_callback", # Enable custom dashboard widgets
    "EXTENSIONS": {
        "modeltranslation": {
            "flags": {
                "en": "🇬🇧",
                "fr": "🇫🇷",
            },
        },
    },
    "STYLES": [
        # Custom styles can be added here if needed
    ],
    "SCRIPTS": [
        "/static/tinymce/tinymce.min.js",
    ],
    "TABS": [
        {
            "models": [
                "accounts.tenant",
                "accounts.branch",
            ],
            "items": [
                {
                    "title": ("Dashboard"),
                    "link": lambda request: "/admin/",
                    "permission": lambda request: request.user.is_superuser,
                },
            ],
        },
    ],
    "COLORS": {
        "primary": {
            "50": "239 246 255",
            "100": "219 234 254",
            "200": "191 219 254",
            "300": "147 197 253",
            "400": "96 165 250",
            "500": "59 130 246",
            "600": "37 99 235",
            "700": "29 78 216",
            "800": "30 64 175",
            "900": "30 58 138",
            "950": "23 37 84",
        },
    },
    "SIDEBAR": {
        "show_search": False,
        "show_all_applications": False,  # Set to False to use custom navigation
        "navigation": [
            {
                "title": "Dashboard",
                "separator": True,
                "items": [
                    {
                        "title": "Overview",
                        "icon": "dashboard",
                        "link": "/admin/",
                    },
                ],
            },
            {
                "title": "Accounts & Users",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Tenants",
                        "icon": "business",
                        "link": "/admin/accounts/tenant/",
                    },
                    {
                        "title": "Branches",
                        "icon": "store",
                        "link": "/admin/accounts/branch/",
                    },
                    {
                        "title": "User Profiles",
                        "icon": "people",
                        "link": "/admin/accounts/userprofile/",
                    },
                    {
                        "title": "Users",
                        "icon": "person",
                        "link": "/admin/auth/user/",
                    },
                    {
                        "title": "Attendance",
                        "icon": "schedule",
                        "link": "/admin/accounts/attendance/",
                    },
                    {
                        "title": "Activity Logs",
                        "icon": "history",
                        "link": "/admin/accounts/activitylog/",
                    },
                    {
                        "title": "System Logs",
                        "icon": "terminal",
                        "link": "/admin/accounts/systemlog/",
                    },
                    {
                        "title": "Cross-Tenant Audit",
                        "icon": "security",
                        "link": "/admin/accounts/crosstenantauditlog/",
                    },
                ],
            },
            {
                "title": "Billing & Subscriptions",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Plans",
                        "icon": "card_membership",
                        "link": "/admin/billing/plan/",
                    },
                    {
                        "title": "Subscriptions",
                        "icon": "subscriptions",
                        "link": "/admin/billing/subscription/",
                    },
                    {
                        "title": "Billing Payments",
                        "icon": "payment",
                        "link": "/admin/billing/payment/",
                    },
                    {
                        "title": "Payment Gateways",
                        "icon": "settings_input_component",
                        "link": "/admin/billing/paymentgatewayconfig/",
                    },
                ],
            },
             {
                "title": "Web Contents",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "FAQs",
                        "icon": "help",
                        "link": "/admin/billing/faq/",
                    },
                    {
                        "title": "Feature Categories",
                        "icon": "category",
                        "link": "/admin/billing/featurecategory/",
                    },
                    {
                        "title": "Feature Items",
                        "icon": "list",
                        "link": "/admin/billing/featureitem/",
                    },
                    {
                        "title": "SEO Settings",
                        "icon": "search",
                        "link": "/admin/accounts/seosettings/",
                    },
                    {
                        "title": "Leadership Members",
                        "icon": "groups",
                        "link": "/admin/billing/leadershipmember/",
                    },
                    {
                        "title": "Contact Messages",
                        "icon": "chat",
                        "link": "/admin/main/contactmessage/",
                    },
                ],
            },
            {
                "title": "Documentation",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Sections",
                        "icon": "folder",
                        "link": "/admin/documentation/documentationsection/",
                    },
                    {
                        "title": "Articles",
                        "icon": "article",
                        "link": "/admin/documentation/documentationarticle/",
                    },
                    {
                        "title": "View Public Manual",
                        "icon": "launch",
                        "link": "/manual/",
                        "target": "_blank",
                    },
                ],
            },
            {
                "title": "Accounts & Security",
                "separator": True,
                "items": [
                    {
                        "title": "Tenants",
                        "icon": "business",
                        "link": "/admin/accounts/tenant/",
                    },
                    {
                        "title": "Branches",
                        "icon": "store",
                        "link": "/admin/accounts/branch/",
                    },
                    {
                        "title": "User Profiles",
                        "icon": "people",
                        "link": "/admin/accounts/userprofile/",
                    },
                    {
                        "title": "API Keys",
                        "icon": "key",
                        "link": "/admin/accounts/apikey/",
                    },
                ],
            },
            {
                "title": "Monitoring",
                "separator": True,
                "items": [
                    {
                        "title": "Attendance",
                        "icon": "schedule",
                        "link": "/admin/accounts/attendance/",
                    },
                    {
                        "title": "Database Backups",
                        "icon": "backup",
                        "link": "/admin/main/databasebackup/",
                        "permission": lambda request: request.user.is_superuser or request.user.has_perm('main.can_download_backup'),
                    },
                    {
                        "title": "Cross-Tenant Audit",
                        "icon": "security",
                        "link": "/admin/accounts/crosstenantauditlog/",
                    },
                ],
            },
            {
                "title": "Notifications",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Notifications",
                        "icon": "notifications",
                        "link": "/admin/notifications/notification/",
                    },
                    {
                        "title": "Notification Settings",
                        "icon": "settings",
                        "link": "/admin/notifications/notificationsetting/",
                    },
                ],
            },
        ],
    },
}

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': str(BASE_DIR / 'django_errors.log'),
            'formatter': 'verbose',
        },
        'db_log': {
            'level': 'WARNING',  # Only save Warnings and Errors to DB to avoid spam
            'class': 'possystem.log_handlers.DatabaseLogHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file', 'db_log'],
            'level': 'INFO',
            'propagate': True,
        },
        'possystem': {
            'handlers': ['console', 'file', 'db_log'],
            'level': 'INFO',
            'propagate': False,
        },
        'branches': {
            'handlers': ['console', 'file', 'db_log'],
            'level': 'INFO',
            'propagate': False,
        },
        'main': {
            'handlers': ['console', 'file', 'db_log'],
            'level': 'INFO',
            'propagate': False,
        },
        'billing': {
            'handlers': ['console', 'file', 'db_log'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'accounts': {
            'handlers': ['console', 'file', 'db_log'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Environment badge for Unfold admin
def get_environment_badge(request):
    """Display current schema as environment badge"""
    from django.db import connection
    schema_name = getattr(connection, 'schema_name', 'public')
    
    if schema_name == 'public':
        return ["Global Admin", "success"]  # Green badge
    else:
        try:
            from accounts.models import Tenant
            tenant = Tenant.objects.get(schema_name=schema_name)
            return [f"Store: {tenant.name}", "info"]  # Blue badge
        except:
            return [schema_name, "warning"]  # Yellow badge

# REST API Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'api.auth.APIKeyAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'api.auth.RequireAPIKey',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
}

# CORS Configuration - Use specific origins in production
_cors_origins = config('CORS_ALLOWED_ORIGINS', default='')
if _cors_origins:
    CORS_ALLOWED_ORIGINS = [origin.strip() for origin in _cors_origins.split(',') if origin.strip()]
    CORS_ALLOW_ALL_ORIGINS = False
else:
    # Fallback for development only
    CORS_ALLOW_ALL_ORIGINS = config('DEBUG', default=False, cast=bool)

# Swagger Configuration
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': 'JWT Access Token. Format: "Bearer {token}"'
        }
    },
    'USE_SESSION_AUTH': True,
    'JSON_EDITOR': True,
}

# TinyMCE Configuration
TINYMCE_JS_URL = '/static/tinymce/tinymce.min.js'
TINYMCE_COMPRESSOR = False
TINYMCE_DEFAULT_CONFIG = {
    "height": "500px",
    "width": "auto",
    "menubar": "file edit view insert format tools table help",
    "plugins": "advlist autolink lists link image charmap print preview anchor searchreplace visualblocks code fullscreen insertdatetime media table paste code help wordcount",
    "toolbar": "undo redo | formatselect | bold italic backcolor | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | removeformat | help",
    "content_style": "body { font-family:Inter,sans-serif; font-size:14px; }",
    "relative_urls": False,
    "remove_script_host": False,
    "convert_urls": True,
    "promotion": False,
    "branding": False,
}

# =============================================================================
# EMAIL CONFIGURATION
# =============================================================================
# Configure your own email server for sending emails

EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@possystem.com')
SERVER_EMAIL = config('SERVER_EMAIL', default='server@possystem.com')

# Email timeout settings
EMAIL_TIMEOUT = config('EMAIL_TIMEOUT', default=30, cast=int)

# For development: print emails to console
if DEBUG and not EMAIL_HOST_USER:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'



# =============================================================================
# CELERY CONFIGURATION
# =============================================================================
CELERY_BROKER_URL = config('REDIS_URL', default='redis://localhost:6379/1')
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_RESULT_BACKEND = config('REDIS_URL', default='redis://localhost:6379/1')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'prune-logs-daily': {
        'task': 'accounts.tasks.prune_old_logs',
        'schedule': crontab(hour=3, minute=0), # Daily at 3 AM
        'args': (90,), # 90 days retention
    },
    'process-abandoned-carts': {
        'task': 'storefront.tasks.process_abandoned_carts',
        'schedule': 21600.0,  # Every 6 hours (in seconds)
    },
    'check-low-stock': {
        'task': 'main.tasks.check_low_stock',
        'schedule': 3600.0,  # Every hour (in seconds)
    },
}

# Redis Cache Configuration
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': config('REDIS_URL', default='redis://localhost:6379/1'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    },
    'storefront': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': config('REDIS_URL', default='redis://localhost:6379/1'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
        'KEY_PREFIX': 'storefront'
    }
}

# =============================================================================
# API SECURITY CONFIGURATION
# =============================================================================

# API Audit Logging
ENABLE_API_AUDIT_LOGGING = config('ENABLE_API_AUDIT_LOGGING', default=True, cast=bool)

# IP Whitelisting for sensitive endpoints
# Format: comma-separated list of IPs or CIDR ranges
# Example: "192.168.1.1,10.0.0.0/24,172.16.0.0/16"
WHITELISTED_IPS = config('WHITELISTED_IPS', default='', cast=Csv())

# Webhook Security
WEBHOOK_SECRET = config('WEBHOOK_SECRET', default='')

# Rate Limiting (uses Redis cache)
RATELIMIT_ENABLE = config('RATELIMIT_ENABLE', default=True, cast=bool)
RATELIMIT_USE_CACHE = 'default'  # Use default Redis cache for rate limiting

# =============================================================================
# PRODUCTION SECURITY VALIDATION
# =============================================================================
# Validate security settings on startup (only in production)
if not DEBUG:
    from possystem.validators import SecurityValidator
    SecurityValidator.validate_all()

# =============================================================================
# STRUCTURED LOGGING CONFIGURATION
# =============================================================================
# Use JSON logging in production, console logging in development
from possystem.logging_config import get_logging_config
LOGGING = get_logging_config(debug=DEBUG)
