# Generated by Django 5.2.9 on 2025-12-29 07:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_featurecategory_featureitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadershipMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('image', models.ImageField(help_text='Member portrait (recommended 800x800)', upload_to='leadership/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, help_text='Full LinkedIn profile URL', null=True)),
                ('twitter_url', models.URLField(blank=True, help_text='Full Twitter/X profile URL', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower is first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leadership Member',
                'verbose_name_plural': 'Leadership Members',
                'ordering': ['order', 'name'],
            },
        ),
    ]
