# Generated by Django 5.2.9 on 2025-12-28 21:27

import django.db.models.deletion
import django_tenants.postgresql_backend.base
import utils.encryption
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], max_length=10)),
                ('module', models.CharField(max_length=255)),
                ('message', utils.encryption.EncryptedTextField()),
                ('traceback', utils.encryption.EncryptedTextField(blank=True, null=True)),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'System Log',
                'verbose_name_plural': 'System Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('subdomain', models.CharField(help_text='Used for schema name', max_length=100, unique=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('tenant_type', models.CharField(choices=[('standard', 'Standard Merchant')], default='standard', help_text='Classification for analytics and billing', max_length=20)),
                ('logo', models.ImageField(blank=True, help_text='Company logo for branding', null=True, upload_to='tenant_logos/')),
                ('address', utils.encryption.EncryptedTextField(blank=True, null=True)),
                ('pos_api_key', utils.encryption.EncryptedTextField(blank=True, help_text='Stored raw key for internal POS use', null=True)),
                ('is_sandbox', models.BooleanField(default=False, help_text='Is this a test/sandbox environment?')),
                ('sandbox_wipe_at', models.DateTimeField(blank=True, help_text='When this sandbox data should be wiped/deleted', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meta_title', models.CharField(blank=True, help_text='Default page title for search engines', max_length=150, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='Short summary of the site for search results', null=True)),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255, null=True)),
                ('og_title', models.CharField(blank=True, help_text='Title shown when sharing on social media', max_length=150, null=True)),
                ('og_description', models.TextField(blank=True, help_text='Description shown when sharing', null=True)),
                ('og_image', models.ImageField(blank=True, help_text='Image shown when sharing (1200x630 recommended)', null=True, upload_to='seo/og_images/')),
                ('google_analytics_id', models.CharField(blank=True, help_text='G-XXXXXXXXXX', max_length=50, null=True)),
                ('facebook_pixel_id', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo_settings', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'SEO Setting',
                'verbose_name_plural': 'SEO Settings',
            },
        ),
        migrations.CreateModel(
            name='GlobalOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', utils.encryption.EncryptedTextField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_orders', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'Global Order (Synced)',
                'verbose_name_plural': 'Global Orders (Synced)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalSystem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('client_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('client_secret_hash', models.CharField(editable=False, max_length=128)),
                ('redirect_uris', models.JSONField(blank=True, default=list, help_text='List of allowed redirect URIs')),
                ('webhook_url', models.URLField(blank=True, null=True)),
                ('icon', models.CharField(default='rocket_launch', help_text='Material symbol name for the icon', max_length=50)),
                ('is_public', models.BooleanField(default=False, help_text='Make this app available in the Marketplace')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_systems', to='accounts.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='accounts.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('unique_id', utils.encryption.EncryptedTextField(blank=True, db_index=True, help_text='Human-readable branch identifier (e.g., BR-0001)', max_length=20, null=True, unique=True)),
                ('address', utils.encryption.EncryptedTextField(blank=True, null=True)),
                ('phone', utils.encryption.EncryptedTextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(blank=True, help_text='Branch logo for receipts', null=True, upload_to='branch_logos/')),
                ('low_stock_threshold', models.PositiveIntegerField(default=10)),
                ('currency_symbol', models.CharField(default='$', max_length=5)),
                ('currency_code', models.CharField(choices=[('USD', 'USD - US Dollar'), ('NGN', 'NGN - Nigerian Naira'), ('GHS', 'GHS - Ghanaian Cedi'), ('ZAR', 'ZAR - South African Rand'), ('EUR', 'EUR - Euro'), ('GBP', 'GBP - British Pound')], default='USD', max_length=3)),
                ('receipt_header', models.TextField(blank=True, help_text='Text to appear at top of receipts', null=True)),
                ('receipt_footer', models.TextField(blank=True, help_text='Text to appear at bottom of receipts', null=True)),
                ('branch_type', models.CharField(choices=[('retail', 'Retail'), ('wholesale', 'Wholesale')], default='retail', max_length=20)),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='Last successful sync timestamp', null=True)),
                ('sync_status', models.CharField(choices=[('healthy', 'Healthy'), ('warning', 'Warning'), ('error', 'Error')], default='healthy', help_text='Current sync health status', max_length=20)),
                ('pending_sync_count', models.PositiveIntegerField(default=0, help_text='Number of pending sync items')),
                ('sync_error_message', models.TextField(blank=True, help_text='Last sync error if any', null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='accounts.tenant')),
            ],
            options={
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('procurement_manager', 'Procurement Manager'), ('sales', 'Sales Man'), ('financial', 'Financial'), ('supplier', 'Supplier')], db_index=True, default='sales', max_length=50)),
                ('can_perform_credit_sales', models.BooleanField(default=False, help_text='Designates whether the salesperson can process transactions using credit as a payment method.')),
                ('is_2fa_enabled', models.BooleanField(default=False)),
                ('otp_secret', utils.encryption.EncryptedTextField(blank=True, null=True)),
                ('pos_pin', utils.encryption.EncryptedTextField(blank=True, help_text='4-6 digit numeric PIN for fast POS access', null=True)),
                ('is_email_verified', models.BooleanField(default=False, help_text='Has the user verified their email address?')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.branch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'tenant')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clock_in', models.DateTimeField(auto_now_add=True)),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='accounts.branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('export', 'Data Export'), ('backup', 'Data Backup')], max_length=20)),
                ('target_model', models.CharField(blank=True, max_length=100)),
                ('target_object_id', models.CharField(blank=True, max_length=100)),
                ('description', utils.encryption.EncryptedTextField()),
                ('changes', models.JSONField(blank=True, help_text='Detailed field-level changes (Old vs New)', null=True)),
                ('ip_address', utils.encryption.EncryptedTextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='accounts.tenant')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='accounts.userprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(help_text='The URL where we will send POST requests')),
                ('secret', models.CharField(help_text='Used to sign the webhook payload', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('events', models.JSONField(default=list, help_text="List of subscribed events (e.g., ['order.created', 'inventory.low'])")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhooks', to='accounts.externalsystem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to='accounts.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('signature', models.CharField(blank=True, help_text='HMAC-SHA256 signature of payload', max_length=128, null=True)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='accounts.webhookendpoint')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CrossTenantAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('access', 'Accessed Tenant'), ('view', 'Viewed Object'), ('add', 'Added Object'), ('change', 'Changed Object'), ('delete', 'Deleted Object')], max_length=20)),
                ('target_model', models.CharField(blank=True, help_text='Model that was accessed/modified', max_length=100)),
                ('target_object_id', models.CharField(blank=True, help_text='ID of the object', max_length=100)),
                ('target_object_repr', models.CharField(blank=True, help_text='String representation of object', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cross_tenant_actions', to=settings.AUTH_USER_MODEL)),
                ('accessed_tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='accounts.tenant')),
                ('user_home_tenant', models.ForeignKey(help_text="User's original tenant", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_audit_logs', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'Cross-Tenant Audit Log',
                'verbose_name_plural': 'Cross-Tenant Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='accounts_cr_user_id_c4dac5_idx'), models.Index(fields=['accessed_tenant', '-timestamp'], name='accounts_cr_accesse_2f90cc_idx'), models.Index(fields=['action_type', '-timestamp'], name='accounts_cr_action__9600e7_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_audit_logs', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'action'], name='accounts_au_timesta_03ca0b_idx'), models.Index(fields=['user', 'action'], name='accounts_au_user_id_96c97d_idx')],
            },
        ),
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('method', models.CharField(max_length=10)),
                ('endpoint', models.CharField(db_index=True, max_length=255)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('request_body', models.JSONField(blank=True, default=dict)),
                ('response_body', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_logs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_logs', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'endpoint'], name='accounts_ap_timesta_983d33_idx'), models.Index(fields=['status_code'], name='accounts_ap_status__51db22_idx')],
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Label for the key (e.g., 'Mobile App')", max_length=100)),
                ('key_prefix', models.CharField(editable=False, max_length=8)),
                ('key_hash', models.CharField(editable=False, help_text='SHA-256 hash of the full key', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_sandbox', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='accounts.branch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'indexes': [models.Index(fields=['key_prefix'], name='accounts_ap_key_pre_553cd9_idx')],
            },
        ),
    ]
