# Generated by Django 5.2.9 on 2025-12-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('procurement_manager', 'Procurement Manager'), ('sales', 'Sales Person'), ('financial', 'Financial'), ('supplier', 'Supplier')], db_index=True, default='sales', max_length=50),
        ),
    ]
