# Generated by Django 5.2.9 on 2025-12-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='seosettings',
            name='homepage_video_id',
            field=models.CharField(blank=True, default='dQw4w9WgXcQ', help_text='YouTube Video ID for the homepage demo (e.g., dQw4w9WgXcQ)', max_length=50, null=True),
        ),
    ]
