# Generated by Django 5.2.9 on 2025-12-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_seosettings_homepage_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='seosettings',
            name='contact_address',
            field=models.TextField(blank=True, default='123 Tech Boulevard, Suite 400\nSan Francisco, CA 94107', null=True),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='contact_email',
            field=models.EmailField(blank=True, default='info@puxbay.com', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='contact_phone',
            field=models.CharField(blank=True, default='+1 (555) 123-4567', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='office_hours',
            field=models.CharField(blank=True, default='Mon-Fri 9am-5pm EST', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='support_email',
            field=models.EmailField(blank=True, default='support@puxbay.com', max_length=254, null=True),
        ),
    ]
