# Generated by Django 5.2.9 on 2025-12-29 03:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email_verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token for email verification'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text="Whether the customer's email has been verified"),
        ),
    ]
