# Generated by Django 5.2.9 on 2025-12-29 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_featurecategory_featureitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featureitem',
            name='category',
        ),
        migrations.DeleteModel(
            name='FeatureCategory',
        ),
        migrations.DeleteModel(
            name='FeatureItem',
        ),
    ]
