# Generated by Django 5.2.9 on 2025-12-29 02:52

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0001_initial'),
    ]

    operations = [
        TrigramExtension(),
    ]
