# Generated by Django 5.2.9 on 2026-01-01 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0002_install_trigram'),
    ]

    operations = [
        migrations.AddField(
            model_name='storefrontsettings',
            name='enable_mobile_money',
            field=models.BooleanField(default=False),
        ),
    ]
